plugins: stylelint-prettier
extends:
  - stylelint-config-standard
  - stylelint-config-recommended-scss
  - stylelint-config-recess-order
  - stylelint-config-prettier
ignoreFiles: 
rules:
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
      - include
      - mixin
      - forward
      - use
      - extend
  property-no-unknown:
    - true
  no-invalid-double-slash-comments:
    - null
  selector-class-pattern:
    - null
  no-descending-specificity:
    - null
  no-irregular-whitespace:
    - null
